services:
  ocr-app:
    build: ./docker
    environment:
      - ROS_DOMAIN_ID=10
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      # mount X11 socket
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - /dev:/dev
      - .:/app
    network_mode: host